config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :scripts, only: %i[new create]
  get '/scripts', to: 'scripts#new'

  resource :optimize, only: %i[new create]
  get '/optimize', to: 'optimize#new'

  # to respond to health checks.
  get '/health', to: 'health#index'

  root 'scripts#new'
end

app/models/forms/optimizer.rb
# frozen_string_literal: true

require 'ipaddr'

module Forms
  # Optimize scripts
  class Optimizer
    include ActiveModel::Model

    attr_accessor :name
    attr_reader :result

    validates :name, presence: true, unless: :proxies_fixed?
    validates :name, inclusion: { in: ProxyList.entries.map(&:value) }, if: :proxies_fixed?
    validate :script_valid?, if: -> { errors.empty? }
    validate :optimize, if: -> { errors.empty? }

    # Set @return to compressed script
    # @return [String] compressed script
    def optimize
      opts = { output: { beautify: false }, mangle: true, harmony: true }
      @result = ProxyPacRb::ProxyPacCompressor.new(options: opts).compress(script)
    rescue StandardError, Uglifier::Error => e
      errors.add(:name, "Script invalid: #{e.message}")
    end

    private

    # @return [ProxyPacRb::ProxyPacxxx]
    # memoize it
    def script
      @script ||= Parser.new.call(name:)
    end

    # validate the script
    def script_valid?
      errors.add(:name, script.message) unless script.valid
    end

    def proxies_fixed?
      ProxyList.entries.any?
    end
  end
end

app/models/forms/script.rb
# frozen_string_literal: true

require 'ipaddr'

module Forms
  # hold the interface to ProxyPacRb
  class Script
    include ActiveModel::Model

    attr_accessor :ip, :name, :url

    validate :ip_valid?
    validates :name, presence: true, unless: :proxies_fixed?
    validates :name, inclusion: { in: ProxyList.entries.map(&:value) }, if: :proxies_fixed?
    validates :url, presence: true
    validate :script_valid?, if: -> { errors.empty? }

    # @return [Array] of Hash(url:, result:)
    def proxies
      url.split.each_with_object([]) do |l_url, a|
        a << { url: l_url, result: proxy(l_url) }
      end
    end

    private

    # @return [String] script result for url and ip
    def proxy(url)
      parser.find(url)
    end

    # @return [ProxyPacRb::ProxyPacFile]
    # memoize it
    def parser
      @parser ||= Parser.new.call(name:, ip:)
    end

    # validate the script
    def script_valid?
      errors.add(:name, parser.message) unless parser.valid
    end

    # validate that ip is a valid IPV4 address
    # @return [Binary] true or false
    def ip_valid?
      return true if ip.blank?

      IPAddr.new(ip.strip, Socket::AF_INET)
    rescue IPAddr::InvalidAddressError, IPAddr::AddressFamilyError
      errors.add(:ip, :invalid)
    end

    def proxies_fixed?
      ProxyList.entries.any?
    end
  end
end

app/models/proxy_list.rb
# frozen_string_literal: true

# manage proxy list
class ProxyList
  class << self
    # @return [Array] of Smash (memoized)
    def entries
      @all = load_records unless defined?(@all)
      @all
    end

    private

    # load and decode PROXIES env variable
    def load_records
      load_env.each_with_object([]) do |entry, acc|
        name, url = entry.split(';')
        text = "#{name} | #{url}"
        acc << Smash.new(label: text, value: url)
      end
    end

    def load_env
      ENV['PROXIES']&.split(',') || []
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Application controller
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/health_controller.rb
# frozen_string_literal: true

# Manage health checks
class HealthController < ApplicationController
  layout false

  def index
    # default always return OK. We assume rails is working
    # to check more (ex: db) add code here and return head :service_unavailable if check fail
    head :ok
  end
end

app/controllers/optimize_controller.rb
# frozen_string_literal: true

# Manage optimizer page
class OptimizeController < ApplicationController
  before_action :allowed?

  def new
    @optimizer = Forms::Optimizer.new
  end

  def create
    @optimizer = Forms::Optimizer.new(optimize_params)
    optimizer.valid? ? send_data(optimizer.result, filename: 'proxy.pac') : render(:new, status: :unprocessable_entity)
  end

  private

  attr_reader :optimizer

  def optimize_params
    params.expect(forms_optimizer: [:name])
  end

  def allowed?
    redirect_to root_path if ENV['NO_COMPRESS_BUTTON']
  end
end

app/controllers/scripts_controller.rb
# frozen_string_literal: true

# Manage script page
class ScriptsController < ApplicationController
  def new
    @script = Forms::Script.new(ip: request.remote_ip)
  end

  def create
    @script = Forms::Script.new(script_params)
    script.valid? ? render(status: :ok) : render(:new, status: :unprocessable_entity)
  end

  private

  attr_reader :script

  def script_params
    params.expect(forms_script: %i[ip name action url])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Helpers used in views
module ApplicationHelper
  def top_suffix
    "-#{Rails.env}" unless Rails.env.production?
  end

  def top_logo
    ENV.fetch('LOGO', 'logo_empty.png')
  end

  def compress?
    ENV['NO_COMPRESS_BUTTON'] ? false : true
  end

  def proxy_list
    ProxyList.entries
  end
end

app/views/home/_form.html.erb
<div class="card">
  <div class="card-divider">
    <h5 class="text-center">Client details</h5>
  </div>
  <div class="card-section">
    <%= simple_form_for @script, remote: true, url: script_path, html: { id: 'url_form' } do |f| %>
        <div class="form-inputs clearfix">
          <%= f.error_notification %>
          <%= f.input :name, as: :text, label: 'Script or script URL<input id="compress" class="hide button tiny secondary no-margin float-right" data-disable-with="Wait..." value="Compress script" type="submit">'.html_safe, placeholder: 'Script or url', required: true %>
          <%= f.input :ip, label: 'IP', placeholder: 'Client IP', required: false %>
          <%= f.input :url, as: :text, label: 'URL(s)<button id="clear" class="hide button tiny secondary no-margin float-right">Clear</button>'.html_safe, placeholder: 'URL(s) to validate', required: false %>
          <%= f.hidden_field :action, required: false %>
          <small>* mandatory field</small>
          <div class="form-actions button-group clearfix">
            <%= f.button :submit, 'Run', id: 'url', data: { disable_with: 'Wait...' } %>
          </div>
        </div>
    <% end %>
  </div>
  <div class="results hide">
    <div class="card-divider clearfix">
      <hr>
      <h5 class="text-center">Results<button id="reset" class="button tiny secondary float-right">Clear results</button></h5>
    </div>
    <div class="card-section">
      <table id="result">
        <thead>
        <tr>
          <td>Url</td>
          <td>Proxy used</td>
        </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="row">
  <div class="large-12 columns" id="form">
    <%= render 'form' %>
  </div>
</div>

app/views/home/script.js.erb
$('#form').html('<%= j (render "form") %>').foundation();
window.all_visibility();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  <title><%= content_for?(:title) ? yield(:title) : 'Proxy Check' %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
  <%= javascript_importmap_tags %>
</head>

<body>
<%= render 'shared/top_navbar' %>
<%= yield %>
</body>
</html>

app/views/optimize/_form.html.erb
<header class="card-header">
  <p class="card-header-title">
    Optimize script
  </p>
</header>
<div class="card-content">
  <div class="content">
    <%= simple_form_for @optimizer, wrapper: :vertical_form, url: optimize_path, html: { id: 'compress_form', data: { turbo: false } } do |f| %>
      <%= f.error_notification %>
      <% if proxy_list&.any? %>
        <%= f.input :name, collection: proxy_list, label_method: :label, value_method: :value, label: 'Name', required: true, prompt: 'select proxy to use' %>
      <% else %>
        <%= f.input :name, as: :text, label: 'Script or script URL', placeholder: 'Script or script url', required: true %>
      <% end %>
      <div class="field">
        <div class="control">
          <%= f.button :submit, 'Optimize', id: 'url', class: 'is-link',
                       data: { disable_with: 'Wait...', action: "click->clear#clear_error" } %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/optimize/create.html.erb
<div data-controller="clear">
  <turbo-frame id="section_1">
    <section class="section" id="form">
      <div class="card">
        <%= render 'form' %>
      </div>
    </section>
  </turbo-frame>
</div>

app/views/optimize/new.html.erb
<div data-controller="clear">
  <turbo-frame id="section_1">
    <section class="section" id="form">
      <div class="card">
        <%= render 'form' %>
      </div>
    </section>
  </turbo-frame>
</div>
<footer class="footer">
  <div class="panel">
    <p class="panel-heading">Return a optimized version of the given .pac file. It can replace the original one
      without loosing functionality, but with a smaller size.</p>
    <a class="panel-block"><strong>Script</strong>: url of your .pac file (http://...../xxx.pac) or the content of a
      .pac file.</a>
    <a class="panel-block is-size-7"><strong>*</strong>: mandatory field.</a>
  </div>
</footer>

app/views/scripts/_form.html.erb
<header class="card-header">
  <p class="card-header-title">
    Client details
  </p>
</header>
<div class="card-content">
  <div class="content">
    <%= simple_form_for @script, wrapper: :vertical_form, url: scripts_path, html: { id: 'url_form', data: { turbo_frame: 'result' } } do |f| %>
      <%= f.error_notification %>
      <% if proxy_list.any? %>
        <%= f.input :name, collection: proxy_list, label_method: :label, value_method: :value, label: 'Name',
                    required: true, prompt: 'select proxy to use' %>
      <% else %>
        <%= f.input :name, as: :text, label: 'Script or script URL', placeholder: 'Script or script url', required: true,
                    wrapper: :input_addons,
                    addons: '<a class="button" data-action="click->clear#clear_name">Clear</a>' %>
      <% end %>
      <%= f.input :ip, label: 'IP', placeholder: 'Client IPv4 (default to 127.0.0.1)', required: false %>
      <%= f.input :url, as: :text, label: 'URL(s)', placeholder: 'URL(s) to validate', required: true,
                  wrapper: :input_addons,
                  addons: '<a class="button" data-action="click->clear#clear_url">Clear</a>' %>
      <div class="field">
        <div class="control">
          <%= f.button :submit, 'Run', id: 'url', class: 'is-link',
                       data: { disable_with: 'Wait...', action: "click->clear#clear_error" } %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/scripts/create.html.erb
<div data-controller="clear">
  <turbo-frame id="result">
    <section class="section" id="result" data-clear-target="error">
      <div class="card">
        <header class="card-header">
          <p class="card-header-title">
            Results
          </p>
        </header>
        <div class="card-content">
          <div class="content">
            <table id="result">
              <thead>
              <tr>
                <td><strong>Url</strong></td>
                <td><strong>Proxy used</strong></td>
              </tr>
              </thead>
              <tbody>
              <% @script.proxies.each do |p| %>
                <tr>
                  <td><%= p[:url] %></td>
                  <td><%= p[:result] %></td>
                </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </section>
  </turbo-frame>
</div>

app/views/scripts/new.html.erb
<div data-controller="clear">
  <turbo-frame id="section_1">
    <section class="section" id="form">
      <div class="card">
        <%= render 'form' %>
      </div>
    </section>
  </turbo-frame>
  <turbo-frame id="result">
  </turbo-frame>
</div>
<footer class="footer">
  <div class="panel">
    <p class="panel-heading">Displays the execution results of a .pac file used by a terminal on the given IP for a list of URLs. </p>
    <a class="panel-block"><strong>Script</strong>: url of a .pac file (http://...../xxx.pac) or the content of a
      .pac file. With a content, you can edit the script and test your changes.</a>
    <a class="panel-block"><strong>IP</strong>: IP of the terminal.</a>
    <a class="panel-block"><strong>URL(s)</strong>: List of URLs to check. One by line.</a>
    <a class="panel-block is-size-7"><strong>*</strong>: mandatory field.</a>
  </div>
</footer>

app/views/shared/_top_menu.html.erb
<div class="navbar-start">
  <% if compress? %>
    <div class="navbar-item has-dropdown is-hoverable">
      <a class="navbar-link">Menu</a>
      <div class="navbar-dropdown is-boxed">
        <%= link_to 'URL', new_scripts_path, class: "navbar-item" %>
        <%= link_to 'Optimize', new_optimize_path, class: "navbar-item" %>
      </div>
    </div>
  <%- end -%>
</div>

<div class="navbar-end">
  <div class="navbar-item has-dropdown is-hoverable is-right">
    <div class="navbar-link is-arrowless">Theme</div>
    <div class="navbar-dropdown is-right is-boxed">
      <div class="navbar-item" data-controller="theme">
        <div class="control">
          <div class="select">
            <label>
              <select class="select" name="theme_select" data-theme-target="themeBtn" data-action="click->theme#toggle">
                <option value="auto">auto</option>
                <option value="dark">dark</option>
                <option value="light">light</option>
              </select>
            </label>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar-item has-dropdown is-hoverable">
    <a class="navbar-link is-arrowless">Help</a>
    <div class="navbar-dropdown is-boxed is-right">
      <a class="navbar-item">
        <small><%= "Version: #{AppVersion}" %></small>
      </a>
    </div>
  </div>
</div>

app/views/shared/_top_navbar.html.erb
<nav class="navbar" data-controller="burger">
  <div class="navbar-brand">
    <a class="navbar-item" href="/"><%= image_tag(top_logo) %></a>
    <div class="navbar-item">Proxy Check<%= top_suffix %></div>
    <a role="button" class='navbar-burger' data-action="click->burger#toggle" data-burger-target="menu" aria-label="menu"
       aria-expanded="false">
      <span aria-hidden="true" />
      <span aria-hidden="true" />
      <span aria-hidden="true" />
    </a>
  </div>
  <div class='navbar-menu' data-burger-target="menu">
    <%= render 'shared/top_menu' %>
  </div>
</nav>